package com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property_key;

import com.speedment.core.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.beacon_property_key'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface BeaconPropertyKeyBuilder extends BeaconPropertyKey, Buildable<BeaconPropertyKey> {
    
    BeaconPropertyKeyBuilder setId(Integer id);
    
    BeaconPropertyKeyBuilder setKey(String key);
}