package com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property_key;

import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property.BeaconProperty;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property.BeaconPropertyField;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property.BeaconPropertyManager;
import com.speedment.core.core.entity.Entity;
import com.speedment.core.manager.metaresult.MetaResult;
import com.speedment.util.json.Json;
import java.lang.Integer;
import java.util.Objects;
import java.util.Optional;
import java.util.function.Consumer;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.beacon_property_key'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
@Entity(managerType = BeaconPropertyKeyManager.class,
        builderType = BeaconPropertyKeyBuilder.class,
        primaryKeyType = Integer.class)
public interface BeaconPropertyKey {
    
    Integer getId();
    
    String getKey();
    
    default Stream<BeaconProperty> beaconPropertiesByKey() {
        return BeaconPropertyManager.get()
                .stream().filter(BeaconPropertyField.KEY.equal(this.getId()));
    }
    
    default Stream<BeaconProperty> beaconProperties() {
        return beaconPropertiesByKey();
    }
    
    static BeaconPropertyKeyBuilder builder() {
        return BeaconPropertyKeyManager.get().builder();
    }
    
    default BeaconPropertyKeyBuilder toBuilder() {
        return BeaconPropertyKeyManager.get().toBuilder(this);
    }
    
    default String toJson() {
        return BeaconPropertyKeyManager.get().toJson(this);
    }
    
    default String toJson(Json<BeaconPropertyKey> json) {
        return json.build(this);
    }
    
    static Stream<BeaconPropertyKey> stream() {
        return BeaconPropertyKeyManager.get().stream();
    }
    
    default Optional<BeaconPropertyKey> persist() {
        return BeaconPropertyKeyManager.get().persist(this);
    }
    
    default Optional<BeaconPropertyKey> update() {
        return BeaconPropertyKeyManager.get().update(this);
    }
    
    default Optional<BeaconPropertyKey> remove() {
        return BeaconPropertyKeyManager.get().remove(this);
    }
    
    default Optional<BeaconPropertyKey> persist(Consumer<MetaResult<BeaconPropertyKey>> listener) {
        return BeaconPropertyKeyManager.get().persist(this, listener);
    }
    
    default Optional<BeaconPropertyKey> update(Consumer<MetaResult<BeaconPropertyKey>> listener) {
        return BeaconPropertyKeyManager.get().update(this, listener);
    }
    
    default Optional<BeaconPropertyKey> remove(Consumer<MetaResult<BeaconPropertyKey>> listener) {
        return BeaconPropertyKeyManager.get().remove(this, listener);
    }
}