package com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property_key;

import com.speedment.core.config.model.Column;
import com.speedment.core.config.model.Table;
import com.speedment.core.manager.sql.SqlManager;
import com.speedment.core.platform.Platform;
import com.speedment.core.platform.component.ManagerComponent;
import com.speedment.core.platform.component.ProjectComponent;
import java.lang.IllegalArgumentException;
import java.lang.Integer;
import java.lang.String;
import javax.annotation.Generated;

/**
 * A manager representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.beacon_property_key'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface BeaconPropertyKeyManager extends SqlManager<Integer, BeaconPropertyKey, BeaconPropertyKeyBuilder> {
    
    @Override
    default Integer primaryKeyFor(BeaconPropertyKey entity) {
        return entity.getId();
    }
    
    @Override
    default Table getTable() {
        return Platform.get().get(ProjectComponent.class).getProject().findTableByName("db0.speedment_stat.beacon_property_key");
    }
    
    @Override
    default Class<BeaconPropertyKeyManager> getManagerClass() {
        return BeaconPropertyKeyManager.class;
    }
    
    @Override
    default Class<BeaconPropertyKey> getEntityClass() {
        return BeaconPropertyKey.class;
    }
    
    @Override
    default Class<BeaconPropertyKeyBuilder> getBuilderClass() {
        return BeaconPropertyKeyBuilder.class;
    }
    
    @Override
    default Object get(BeaconPropertyKey entity, Column column) {
        switch (column.getName()) {
            case "id" : return entity.getId();
            case "key" : return entity.getKey();
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @Override
    default void set(BeaconPropertyKeyBuilder entity, Column column, Object value) {
        switch (column.getName()) {
            case "id" : entity.setId((Integer) value); break;
            case "key" : entity.setKey((String) value); break;
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @SuppressWarnings("unchecked")
    static BeaconPropertyKeyManager get() {
        return Platform.get().get(ManagerComponent.class).manager(BeaconPropertyKeyManager.class);
    }
}