package com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property_key.impl;

import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property_key.BeaconPropertyKey;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property_key.BeaconPropertyKeyBuilder;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.beacon_property_key'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class BeaconPropertyKeyImpl implements BeaconPropertyKeyBuilder {
    
    private Integer id;
    private String key;
    
    public BeaconPropertyKeyImpl() {
        
    }
    
    public BeaconPropertyKeyImpl(final BeaconPropertyKey beaconPropertyKey) {
        setId(beaconPropertyKey.getId());
        setKey(beaconPropertyKey.getKey());
    }
    
    @Override
    public Integer getId() {
        return id;
    }
    
    @Override
    public final BeaconPropertyKeyImpl setId(Integer id) {
        this.id = id;
        return this;
    }
    
    @Override
    public String getKey() {
        return key;
    }
    
    @Override
    public final BeaconPropertyKeyImpl setKey(String key) {
        this.key = key;
        return this;
    }
    
    @Override
    public BeaconPropertyKey build() {
        return new BeaconPropertyKeyImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("key = "+Objects.toString(getKey()));
        return "BeaconPropertyKeyImpl "+sj.toString();
    }
}