package com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property_key.impl;

import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property_key.BeaconPropertyKey;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property_key.BeaconPropertyKeyBuilder;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property_key.BeaconPropertyKeyManager;
import com.speedment.core.exception.SpeedmentException;
import com.speedment.core.manager.sql.AbstractSqlManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * A manager implementation representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.beacon_property_key'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class BeaconPropertyKeyManagerImpl extends AbstractSqlManager<Integer, BeaconPropertyKey, BeaconPropertyKeyBuilder> implements BeaconPropertyKeyManager {
    
    public BeaconPropertyKeyManagerImpl() {
        setSqlEntityMapper(this::defaultReadEntity);
    }
    
    @Override
    public BeaconPropertyKeyBuilder builder() {
        return new BeaconPropertyKeyImpl();
    }
    
    @Override
    public BeaconPropertyKeyBuilder toBuilder(BeaconPropertyKey prototype) {
        return new BeaconPropertyKeyImpl(prototype);
    }
    
    protected BeaconPropertyKey defaultReadEntity(ResultSet resultSet) {
        final BeaconPropertyKeyBuilder builder = builder();
        try {
            builder.setId(resultSet.getInt("id"));
            builder.setKey(resultSet.getString("key"));
        }
        catch (SQLException sqle) {
            throw new SpeedmentException(sqle);
        }
        return builder;
    }
}