package com.speedment.beacon.speedment_stat.db0.speedment_stat.frontend;

import com.speedment.core.core.Buildable;
import java.sql.Timestamp;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.frontend'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface FrontendBuilder extends Frontend, Buildable<Frontend> {
    
    FrontendBuilder setId(Long id);
    
    FrontendBuilder setRegId(String regId);
    
    FrontendBuilder setFirstName(String firstName);
    
    FrontendBuilder setLastName(String lastName);
    
    FrontendBuilder setEmail(String email);
    
    FrontendBuilder setOrganization(String organization);
    
    FrontendBuilder setCountry(String country);
    
    FrontendBuilder setPhone(String phone);
    
    FrontendBuilder setVersion(String version);
    
    FrontendBuilder setCoreFullVersion(String coreFullVersion);
    
    FrontendBuilder setCreated(Timestamp created);
    
    FrontendBuilder setIpAddress(String ipAddress);
    
    FrontendBuilder setIpAddressName(String ipAddressName);
    
    FrontendBuilder setRemotePort(Integer remotePort);
    
    FrontendBuilder setComment(String comment);
}