package com.speedment.beacon.speedment_stat.db0.speedment_stat.message;

import com.speedment.core.core.Buildable;
import java.sql.Timestamp;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.message'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface MessageBuilder extends Message, Buildable<Message> {
    
    MessageBuilder setId(Long id);
    
    MessageBuilder setCreated(Timestamp created);
    
    MessageBuilder setIpAddress(String ipAddress);
    
    MessageBuilder setIpAddressName(String ipAddressName);
    
    MessageBuilder setRemotePort(Integer remotePort);
    
    MessageBuilder setGui(String gui);
    
    MessageBuilder setCoreFullVersion(String coreFullVersion);
    
    MessageBuilder setSessionId(String sessionId);
    
    MessageBuilder setVersion(String version);
    
    MessageBuilder setType(String type);
    
    MessageBuilder setRegId(String regId);
}