package com.speedment.beacon.speedment_stat.db0.speedment_stat.usage;

import com.speedment.core.core.Buildable;
import java.sql.Timestamp;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.usage'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface UsageBuilder extends Usage, Buildable<Usage> {
    
    UsageBuilder setId(Integer id);
    
    UsageBuilder setSite(String site);
    
    UsageBuilder setArtifact(String artifact);
    
    UsageBuilder setTimeStamp(Timestamp timeStamp);
    
    UsageBuilder setCount(Integer count);
}