package com.speedment.beacon.speedment_stat.db0.speedment_stat.usage;

import com.speedment.core.core.entity.Entity;
import com.speedment.core.manager.metaresult.MetaResult;
import com.speedment.util.json.Json;
import java.lang.Integer;
import java.sql.Timestamp;
import java.util.Optional;
import java.util.function.Consumer;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * An interface representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.usage'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
@Entity(managerType = UsageManager.class,
        builderType = UsageBuilder.class,
        primaryKeyType = Integer.class)
public interface Usage {
    
    Integer getId();
    
    String getSite();
    
    Optional<String> getArtifact();
    
    Timestamp getTimeStamp();
    
    Optional<Integer> getCount();
    
    static UsageBuilder builder() {
        return UsageManager.get().builder();
    }
    
    default UsageBuilder toBuilder() {
        return UsageManager.get().toBuilder(this);
    }
    
    default String toJson() {
        return UsageManager.get().toJson(this);
    }
    
    default String toJson(Json<Usage> json) {
        return json.build(this);
    }
    
    static Stream<Usage> stream() {
        return UsageManager.get().stream();
    }
    
    default Optional<Usage> persist() {
        return UsageManager.get().persist(this);
    }
    
    default Optional<Usage> update() {
        return UsageManager.get().update(this);
    }
    
    default Optional<Usage> remove() {
        return UsageManager.get().remove(this);
    }
    
    default Optional<Usage> persist(Consumer<MetaResult<Usage>> listener) {
        return UsageManager.get().persist(this, listener);
    }
    
    default Optional<Usage> update(Consumer<MetaResult<Usage>> listener) {
        return UsageManager.get().update(this, listener);
    }
    
    default Optional<Usage> remove(Consumer<MetaResult<Usage>> listener) {
        return UsageManager.get().remove(this, listener);
    }
}