package com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon;

import com.speedment.core.field.reference.ComparableReferenceField;
import com.speedment.core.field.reference.string.StringReferenceField;
import java.sql.Timestamp;
import javax.annotation.Generated;
import static com.speedment.core.field.FieldUtil.findColumn;

/**
 * Interface representing the fields of an entity.
 * 
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public final class BeaconField {
    
    public final static ComparableReferenceField<Beacon, Long> ID = new ComparableReferenceField<>(() -> findColumn(Beacon.class, "id"), Beacon::getId);
    public final static ComparableReferenceField<Beacon, Timestamp> CREATED = new ComparableReferenceField<>(() -> findColumn(Beacon.class, "created"), Beacon::getCreated);
    public final static StringReferenceField<Beacon> IPADDRESS = new StringReferenceField<>(() -> findColumn(Beacon.class, "ipAddress"), Beacon::getIpAddress);
    
    private BeaconField() {
        
    }
}