package com.speedment.beacon.speedment_stat;

import com.speedment.core.runtime.ApplicationMetadata;

/**
 * A Speedment Application Metadata representing an entity (for example, a row) in the Project 'speedment_stat'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
public class SpeedmentStatApplicationMetadata implements ApplicationMetadata {
    
    public SpeedmentStatApplicationMetadata() {
        
    }
    
    @Override
    public String getMetadata() {
        return 
                "import com.speedment.core.config.model.parameters.*\n"+
                "\n"+
                "name = \"speedment_stat\";\n"+
                "packageLocation = \"src/main/java\";\n"+
                "packageName = \"com.speedment.beacon\";\n"+
                "enabled = true;\n"+
                "dbms {\n"+
                "    ipAddress = \"127.0.0.1\";\n"+
                "    name = \"db0\";\n"+
                "    port = 3306;\n"+
                "    type = StandardDbmsType.MYSQL;\n"+
                "    username = \"root\";\n"+
                "    enabled = true;\n"+
                "    schema {\n"+
                "        columnCompressionType = ColumnCompressionType.NONE;\n"+
                "        fieldStorageType = FieldStorageType.WRAPPER;\n"+
                "        name = \"speedment_stat\";\n"+
                "        schemaName = \"speedment_stat\";\n"+
                "        storageEngineType = StorageEngineType.ON_HEAP;\n"+
                "        defaultSchema = false;\n"+
                "        enabled = true;\n"+
                "        table {\n"+
                "            columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "            fieldStorageType = FieldStorageType.INHERIT;\n"+
                "            name = \"TRIGGERLOG\";\n"+
                "            storageEngineType = StorageEngineType.INHERIT;\n"+
                "            tableName = \"TRIGGERLOG\";\n"+
                "            enabled = false;\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Long.class;\n"+
                "                name = \"ID\";\n"+
                "                autoincrement = true;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.sql.Timestamp.class;\n"+
                "                name = \"CTIME\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Byte.class;\n"+
                "                name = \"TYPE_CODE\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"SCHEMA_NAME\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"TABLE_NAME\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"PRIMARYKEY0\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"PRIMARYKEY1\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"PRIMARYKEY2\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"PRIMARYKEY3\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"PRIMARYKEY4\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"PRIMARYKEY5\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"CLIENT_NAME\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            primaryKeyColumn {\n"+
                "                name = \"ID\";\n"+
                "                enabled = true;\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"PRIMARY\";\n"+
                "                enabled = true;\n"+
                "                unique = true;\n"+
                "                indexColumn {\n"+
                "                    name = \"ID\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"index_schema\";\n"+
                "                enabled = true;\n"+
                "                unique = false;\n"+
                "                indexColumn {\n"+
                "                    name = \"SCHEMA_NAME\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"index_table\";\n"+
                "                enabled = true;\n"+
                "                unique = false;\n"+
                "                indexColumn {\n"+
                "                    name = \"TABLE_NAME\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "        }\n"+
                "        table {\n"+
                "            columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "            fieldStorageType = FieldStorageType.INHERIT;\n"+
                "            name = \"beacon\";\n"+
                "            storageEngineType = StorageEngineType.INHERIT;\n"+
                "            tableName = \"beacon\";\n"+
                "            enabled = true;\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Long.class;\n"+
                "                name = \"id\";\n"+
                "                autoincrement = true;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.sql.Timestamp.class;\n"+
                "                name = \"created\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"ipAddress\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            primaryKeyColumn {\n"+
                "                name = \"id\";\n"+
                "                enabled = true;\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"PRIMARY\";\n"+
                "                enabled = true;\n"+
                "                unique = true;\n"+
                "                indexColumn {\n"+
                "                    name = \"id\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"created\";\n"+
                "                enabled = true;\n"+
                "                unique = false;\n"+
                "                indexColumn {\n"+
                "                    name = \"created\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "        }\n"+
                "        table {\n"+
                "            columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "            fieldStorageType = FieldStorageType.INHERIT;\n"+
                "            name = \"beacon_property\";\n"+
                "            storageEngineType = StorageEngineType.INHERIT;\n"+
                "            tableName = \"beacon_property\";\n"+
                "            enabled = true;\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Long.class;\n"+
                "                name = \"beacon\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Integer.class;\n"+
                "                name = \"key\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"value\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            primaryKeyColumn {\n"+
                "                name = \"beacon\";\n"+
                "                enabled = true;\n"+
                "            }\n"+
                "            primaryKeyColumn {\n"+
                "                name = \"key\";\n"+
                "                enabled = true;\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"PRIMARY\";\n"+
                "                enabled = true;\n"+
                "                unique = true;\n"+
                "                indexColumn {\n"+
                "                    name = \"beacon\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "                indexColumn {\n"+
                "                    name = \"key\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"beacon\";\n"+
                "                enabled = true;\n"+
                "                unique = false;\n"+
                "                indexColumn {\n"+
                "                    name = \"beacon\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"key\";\n"+
                "                enabled = true;\n"+
                "                unique = false;\n"+
                "                indexColumn {\n"+
                "                    name = \"key\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            foreignKey {\n"+
                "                name = \"FK_beacon\";\n"+
                "                enabled = true;\n"+
                "                foreignKeyColumn {\n"+
                "                    foreignColumnName = \"id\";\n"+
                "                    foreignTableName = \"beacon\";\n"+
                "                    name = \"beacon\";\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            foreignKey {\n"+
                "                name = \"FK_beacon_property_key\";\n"+
                "                enabled = true;\n"+
                "                foreignKeyColumn {\n"+
                "                    foreignColumnName = \"id\";\n"+
                "                    foreignTableName = \"beacon_property_key\";\n"+
                "                    name = \"key\";\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "        }\n"+
                "        table {\n"+
                "            columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "            fieldStorageType = FieldStorageType.INHERIT;\n"+
                "            name = \"beacon_property_key\";\n"+
                "            storageEngineType = StorageEngineType.INHERIT;\n"+
                "            tableName = \"beacon_property_key\";\n"+
                "            enabled = true;\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Integer.class;\n"+
                "                name = \"id\";\n"+
                "                autoincrement = true;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"key\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            primaryKeyColumn {\n"+
                "                name = \"id\";\n"+
                "                enabled = true;\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"PRIMARY\";\n"+
                "                enabled = true;\n"+
                "                unique = true;\n"+
                "                indexColumn {\n"+
                "                    name = \"id\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"key\";\n"+
                "                enabled = true;\n"+
                "                unique = true;\n"+
                "                indexColumn {\n"+
                "                    name = \"key\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "        }\n"+
                "        table {\n"+
                "            columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "            fieldStorageType = FieldStorageType.INHERIT;\n"+
                "            name = \"frontend\";\n"+
                "            storageEngineType = StorageEngineType.INHERIT;\n"+
                "            tableName = \"frontend\";\n"+
                "            enabled = true;\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Long.class;\n"+
                "                name = \"id\";\n"+
                "                autoincrement = true;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"regId\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"first_name\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"last_name\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"email\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"organization\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"country\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"phone\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"version\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"coreFullVersion\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.sql.Timestamp.class;\n"+
                "                name = \"created\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"ipAddress\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"ipAddressName\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Integer.class;\n"+
                "                name = \"remotePort\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"comment\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            primaryKeyColumn {\n"+
                "                name = \"id\";\n"+
                "                enabled = true;\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"Index_created\";\n"+
                "                enabled = true;\n"+
                "                unique = false;\n"+
                "                indexColumn {\n"+
                "                    name = \"created\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"Index_random\";\n"+
                "                enabled = true;\n"+
                "                unique = false;\n"+
                "                indexColumn {\n"+
                "                    name = \"regId\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"PRIMARY\";\n"+
                "                enabled = true;\n"+
                "                unique = true;\n"+
                "                indexColumn {\n"+
                "                    name = \"id\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "        }\n"+
                "        table {\n"+
                "            columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "            fieldStorageType = FieldStorageType.INHERIT;\n"+
                "            name = \"message\";\n"+
                "            storageEngineType = StorageEngineType.INHERIT;\n"+
                "            tableName = \"message\";\n"+
                "            enabled = true;\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Long.class;\n"+
                "                name = \"id\";\n"+
                "                autoincrement = true;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.sql.Timestamp.class;\n"+
                "                name = \"created\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"ipAddress\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"ipAddressName\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Integer.class;\n"+
                "                name = \"remotePort\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"gui\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"coreFullVersion\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"sessionId\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"version\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"type\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"regId\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            primaryKeyColumn {\n"+
                "                name = \"id\";\n"+
                "                enabled = true;\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"Index_type\";\n"+
                "                enabled = true;\n"+
                "                unique = false;\n"+
                "                indexColumn {\n"+
                "                    name = \"type\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"PRIMARY\";\n"+
                "                enabled = true;\n"+
                "                unique = true;\n"+
                "                indexColumn {\n"+
                "                    name = \"id\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "        }\n"+
                "        table {\n"+
                "            columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "            fieldStorageType = FieldStorageType.INHERIT;\n"+
                "            name = \"message_item\";\n"+
                "            storageEngineType = StorageEngineType.INHERIT;\n"+
                "            tableName = \"message_item\";\n"+
                "            enabled = true;\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Long.class;\n"+
                "                name = \"id\";\n"+
                "                autoincrement = true;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Long.class;\n"+
                "                name = \"message\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"key\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"value\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            primaryKeyColumn {\n"+
                "                name = \"id\";\n"+
                "                enabled = true;\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"FK_message_item_1\";\n"+
                "                enabled = true;\n"+
                "                unique = false;\n"+
                "                indexColumn {\n"+
                "                    name = \"message\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"Index_key\";\n"+
                "                enabled = true;\n"+
                "                unique = false;\n"+
                "                indexColumn {\n"+
                "                    name = \"key\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"PRIMARY\";\n"+
                "                enabled = true;\n"+
                "                unique = true;\n"+
                "                indexColumn {\n"+
                "                    name = \"id\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "            foreignKey {\n"+
                "                name = \"FK_message_item_1\";\n"+
                "                enabled = true;\n"+
                "                foreignKeyColumn {\n"+
                "                    foreignColumnName = \"id\";\n"+
                "                    foreignTableName = \"message\";\n"+
                "                    name = \"message\";\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "        }\n"+
                "        table {\n"+
                "            columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "            fieldStorageType = FieldStorageType.INHERIT;\n"+
                "            name = \"report\";\n"+
                "            storageEngineType = StorageEngineType.INHERIT;\n"+
                "            tableName = \"report\";\n"+
                "            enabled = true;\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Integer.class;\n"+
                "                name = \"id\";\n"+
                "                autoincrement = true;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"title\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"sql\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"chartUrl\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Integer.class;\n"+
                "                name = \"listOrder\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            primaryKeyColumn {\n"+
                "                name = \"id\";\n"+
                "                enabled = true;\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"PRIMARY\";\n"+
                "                enabled = true;\n"+
                "                unique = true;\n"+
                "                indexColumn {\n"+
                "                    name = \"id\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "        }\n"+
                "        table {\n"+
                "            columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "            fieldStorageType = FieldStorageType.INHERIT;\n"+
                "            name = \"usage\";\n"+
                "            storageEngineType = StorageEngineType.INHERIT;\n"+
                "            tableName = \"usage\";\n"+
                "            enabled = true;\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Integer.class;\n"+
                "                name = \"id\";\n"+
                "                autoincrement = true;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"site\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.String.class;\n"+
                "                name = \"artifact\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.sql.Timestamp.class;\n"+
                "                name = \"timeStamp\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = false;\n"+
                "            }\n"+
                "            column {\n"+
                "                columnCompressionType = ColumnCompressionType.INHERIT;\n"+
                "                fieldStorageType = FieldStorageType.INHERIT;\n"+
                "                mapping = java.lang.Integer.class;\n"+
                "                name = \"count\";\n"+
                "                autoincrement = false;\n"+
                "                enabled = true;\n"+
                "                nullable = true;\n"+
                "            }\n"+
                "            primaryKeyColumn {\n"+
                "                name = \"id\";\n"+
                "                enabled = true;\n"+
                "            }\n"+
                "            index {\n"+
                "                name = \"PRIMARY\";\n"+
                "                enabled = true;\n"+
                "                unique = true;\n"+
                "                indexColumn {\n"+
                "                    name = \"id\";\n"+
                "                    orderType = OrderType.ASC;\n"+
                "                    enabled = true;\n"+
                "                }\n"+
                "            }\n"+
                "        }\n"+
                "    }\n"+
                "}\n"+
        "";
    }
}