package com.speedment.beacon.speedment_stat;

import com.speedment.core.runtime.SpeedmentApplicationLifecycle;

/**
 * A Speedment Application Lifecycle representing an entity (for example, a row) in the Project 'speedment_stat'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
public class SpeedmentStatApplication extends SpeedmentApplicationLifecycle<SpeedmentStatApplication> {
    
    public SpeedmentStatApplication() {
        setSpeedmentApplicationMetadata(new SpeedmentStatApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        loadAndSetProject();
        put(new com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon.impl.BeaconManagerImpl());
        put(new com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property.impl.BeaconPropertyManagerImpl());
        put(new com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property_key.impl.BeaconPropertyKeyManagerImpl());
        put(new com.speedment.beacon.speedment_stat.db0.speedment_stat.frontend.impl.FrontendManagerImpl());
        put(new com.speedment.beacon.speedment_stat.db0.speedment_stat.message.impl.MessageManagerImpl());
        put(new com.speedment.beacon.speedment_stat.db0.speedment_stat.message_item.impl.MessageItemManagerImpl());
        put(new com.speedment.beacon.speedment_stat.db0.speedment_stat.report.impl.ReportManagerImpl());
        put(new com.speedment.beacon.speedment_stat.db0.speedment_stat.usage.impl.UsageManagerImpl());
        super.onInit();
    }
}