package com.speedment.beacon.speedment_stat.db0.speedment_stat.message_item.impl;

import com.speedment.beacon.speedment_stat.db0.speedment_stat.message_item.MessageItem;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.message_item.MessageItemBuilder;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.message_item.MessageItemManager;
import com.speedment.core.exception.SpeedmentException;
import com.speedment.core.manager.sql.AbstractSqlManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * A manager implementation representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.message_item'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class MessageItemManagerImpl extends AbstractSqlManager<Long, MessageItem, MessageItemBuilder> implements MessageItemManager {
    
    public MessageItemManagerImpl() {
        setSqlEntityMapper(this::defaultReadEntity);
    }
    
    @Override
    public MessageItemBuilder builder() {
        return new MessageItemImpl();
    }
    
    @Override
    public MessageItemBuilder toBuilder(MessageItem prototype) {
        return new MessageItemImpl(prototype);
    }
    
    protected MessageItem defaultReadEntity(ResultSet resultSet) {
        final MessageItemBuilder builder = builder();
        try {
            builder.setId(resultSet.getLong("id"));
            builder.setMessage(resultSet.getLong("message"));
            builder.setKey(resultSet.getString("key"));
            builder.setValue(resultSet.getString("value"));
        }
        catch (SQLException sqle) {
            throw new SpeedmentException(sqle);
        }
        return builder;
    }
}