package com.speedment.beacon.speedment_stat.db0.speedment_stat.message_item.impl;

import com.speedment.beacon.speedment_stat.db0.speedment_stat.message_item.MessageItem;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.message_item.MessageItemBuilder;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.message_item'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class MessageItemImpl implements MessageItemBuilder {
    
    private Long id;
    private Long message;
    private String key;
    private String value;
    
    public MessageItemImpl() {
        
    }
    
    public MessageItemImpl(final MessageItem messageItem) {
        setId(messageItem.getId());
        setMessage(messageItem.getMessage());
        setKey(messageItem.getKey());
        setValue(messageItem.getValue());
    }
    
    @Override
    public Long getId() {
        return id;
    }
    
    @Override
    public final MessageItemImpl setId(Long id) {
        this.id = id;
        return this;
    }
    
    @Override
    public Long getMessage() {
        return message;
    }
    
    @Override
    public final MessageItemImpl setMessage(Long message) {
        this.message = message;
        return this;
    }
    
    @Override
    public String getKey() {
        return key;
    }
    
    @Override
    public final MessageItemImpl setKey(String key) {
        this.key = key;
        return this;
    }
    
    @Override
    public String getValue() {
        return value;
    }
    
    @Override
    public final MessageItemImpl setValue(String value) {
        this.value = value;
        return this;
    }
    
    @Override
    public MessageItem build() {
        return new MessageItemImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("message = "+Objects.toString(getMessage()));
        sj.add("key = "+Objects.toString(getKey()));
        sj.add("value = "+Objects.toString(getValue()));
        return "MessageItemImpl "+sj.toString();
    }
}