package com.speedment.beacon.speedment_stat.db0.speedment_stat.report;

import com.speedment.core.config.model.Column;
import com.speedment.core.config.model.Table;
import com.speedment.core.manager.sql.SqlManager;
import com.speedment.core.platform.Platform;
import com.speedment.core.platform.component.ManagerComponent;
import com.speedment.core.platform.component.ProjectComponent;
import java.lang.IllegalArgumentException;
import java.lang.Integer;
import java.lang.String;
import javax.annotation.Generated;

/**
 * A manager representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.report'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface ReportManager extends SqlManager<Integer, Report, ReportBuilder> {
    
    @Override
    default Integer primaryKeyFor(Report entity) {
        return entity.getId();
    }
    
    @Override
    default Table getTable() {
        return Platform.get().get(ProjectComponent.class).getProject().findTableByName("db0.speedment_stat.report");
    }
    
    @Override
    default Class<ReportManager> getManagerClass() {
        return ReportManager.class;
    }
    
    @Override
    default Class<Report> getEntityClass() {
        return Report.class;
    }
    
    @Override
    default Class<ReportBuilder> getBuilderClass() {
        return ReportBuilder.class;
    }
    
    @Override
    default Object get(Report entity, Column column) {
        switch (column.getName()) {
            case "id" : return entity.getId();
            case "title" : return entity.getTitle();
            case "sql" : return entity.getSql();
            case "chartUrl" : return entity.getChartUrl();
            case "listOrder" : return entity.getListOrder();
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @Override
    default void set(ReportBuilder entity, Column column, Object value) {
        switch (column.getName()) {
            case "id" : entity.setId((Integer) value); break;
            case "title" : entity.setTitle((String) value); break;
            case "sql" : entity.setSql((String) value); break;
            case "chartUrl" : entity.setChartUrl((String) value); break;
            case "listOrder" : entity.setListOrder((Integer) value); break;
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @SuppressWarnings("unchecked")
    static ReportManager get() {
        return Platform.get().get(ManagerComponent.class).manager(ReportManager.class);
    }
}