package com.speedment.beacon.speedment_stat.db0.speedment_stat.report;

import com.speedment.core.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.report'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface ReportBuilder extends Report, Buildable<Report> {
    
    ReportBuilder setId(Integer id);
    
    ReportBuilder setTitle(String title);
    
    ReportBuilder setSql(String sql);
    
    ReportBuilder setChartUrl(String chartUrl);
    
    ReportBuilder setListOrder(Integer listOrder);
}