package com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property.impl;

import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property.BeaconProperty;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property.BeaconPropertyBuilder;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property.BeaconPropertyManager;
import com.speedment.core.exception.SpeedmentException;
import com.speedment.core.manager.sql.AbstractSqlManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * A manager implementation representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.beacon_property'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class BeaconPropertyManagerImpl extends AbstractSqlManager<List<?>, BeaconProperty, BeaconPropertyBuilder> implements BeaconPropertyManager {
    
    public BeaconPropertyManagerImpl() {
        setSqlEntityMapper(this::defaultReadEntity);
    }
    
    @Override
    public BeaconPropertyBuilder builder() {
        return new BeaconPropertyImpl();
    }
    
    @Override
    public BeaconPropertyBuilder toBuilder(BeaconProperty prototype) {
        return new BeaconPropertyImpl(prototype);
    }
    
    protected BeaconProperty defaultReadEntity(ResultSet resultSet) {
        final BeaconPropertyBuilder builder = builder();
        try {
            builder.setBeacon(resultSet.getLong("beacon"));
            builder.setKey(resultSet.getInt("key"));
            builder.setValue(getString(resultSet, "value"));
        }
        catch (SQLException sqle) {
            throw new SpeedmentException(sqle);
        }
        return builder;
    }
}