package com.speedment.beacon.speedment_stat.db0.speedment_stat.message_item;

import com.speedment.core.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.message_item'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface MessageItemBuilder extends MessageItem, Buildable<MessageItem> {
    
    MessageItemBuilder setId(Long id);
    
    MessageItemBuilder setMessage(Long message);
    
    MessageItemBuilder setKey(String key);
    
    MessageItemBuilder setValue(String value);
}