package com.speedment.beacon.speedment_stat.db0.speedment_stat.message_item;

import com.speedment.core.config.model.Column;
import com.speedment.core.config.model.Table;
import com.speedment.core.manager.sql.SqlManager;
import com.speedment.core.platform.Platform;
import com.speedment.core.platform.component.ManagerComponent;
import com.speedment.core.platform.component.ProjectComponent;
import java.lang.IllegalArgumentException;
import java.lang.Long;
import java.lang.String;
import javax.annotation.Generated;

/**
 * A manager representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.message_item'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface MessageItemManager extends SqlManager<Long, MessageItem, MessageItemBuilder> {
    
    @Override
    default Long primaryKeyFor(MessageItem entity) {
        return entity.getId();
    }
    
    @Override
    default Table getTable() {
        return Platform.get().get(ProjectComponent.class).getProject().findTableByName("db0.speedment_stat.message_item");
    }
    
    @Override
    default Class<MessageItemManager> getManagerClass() {
        return MessageItemManager.class;
    }
    
    @Override
    default Class<MessageItem> getEntityClass() {
        return MessageItem.class;
    }
    
    @Override
    default Class<MessageItemBuilder> getBuilderClass() {
        return MessageItemBuilder.class;
    }
    
    @Override
    default Object get(MessageItem entity, Column column) {
        switch (column.getName()) {
            case "id" : return entity.getId();
            case "message" : return entity.getMessage();
            case "key" : return entity.getKey();
            case "value" : return entity.getValue();
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @Override
    default void set(MessageItemBuilder entity, Column column, Object value) {
        switch (column.getName()) {
            case "id" : entity.setId((Long) value); break;
            case "message" : entity.setMessage((Long) value); break;
            case "key" : entity.setKey((String) value); break;
            case "value" : entity.setValue((String) value); break;
            default : throw new IllegalArgumentException("Unknown column '" + column.getName() + "'.");
        }
    }
    
    @SuppressWarnings("unchecked")
    static MessageItemManager get() {
        return Platform.get().get(ManagerComponent.class).manager(MessageItemManager.class);
    }
}