package com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon_property;

import com.speedment.core.core.Buildable;
import javax.annotation.Generated;

/**
 * A builder representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.beacon_property'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public interface BeaconPropertyBuilder extends BeaconProperty, Buildable<BeaconProperty> {
    
    BeaconPropertyBuilder setBeacon(Long beacon);
    
    BeaconPropertyBuilder setKey(Integer key);
    
    BeaconPropertyBuilder setValue(String value);
}