package com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon.impl;

import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon.Beacon;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon.BeaconBuilder;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon.BeaconManager;
import com.speedment.core.exception.SpeedmentException;
import com.speedment.core.manager.sql.AbstractSqlManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.stream.Stream;
import javax.annotation.Generated;

/**
 * A manager implementation representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.beacon'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class BeaconManagerImpl extends AbstractSqlManager<Long, Beacon, BeaconBuilder> implements BeaconManager {
    
    public BeaconManagerImpl() {
        setSqlEntityMapper(this::defaultReadEntity);
    }
    
    @Override
    public BeaconBuilder builder() {
        return new BeaconImpl();
    }
    
    @Override
    public BeaconBuilder toBuilder(Beacon prototype) {
        return new BeaconImpl(prototype);
    }
    
    protected Beacon defaultReadEntity(ResultSet resultSet) {
        final BeaconBuilder builder = builder();
        try {
            builder.setId(resultSet.getLong("id"));
            builder.setCreated(resultSet.getTimestamp("created"));
            builder.setIpAddress(resultSet.getString("ipAddress"));
        }
        catch (SQLException sqle) {
            throw new SpeedmentException(sqle);
        }
        return builder;
    }
}