package com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon.impl;

import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon.Beacon;
import com.speedment.beacon.speedment_stat.db0.speedment_stat.beacon.BeaconBuilder;
import java.sql.Timestamp;
import java.util.Objects;
import java.util.StringJoiner;
import javax.annotation.Generated;

/**
 * An implementation  representing an entity (for example, a row) in the Table 'speedment_stat.db0.speedment_stat.beacon'.
 * <p>
 * This Class or Interface has been automatically generated by Speedment.
 * Any changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment 
 */
@Generated("Speedment")
public class BeaconImpl implements BeaconBuilder {
    
    private Long id;
    private Timestamp created;
    private String ipAddress;
    
    public BeaconImpl() {
        
    }
    
    public BeaconImpl(final Beacon beacon) {
        setId(beacon.getId());
        setCreated(beacon.getCreated());
        setIpAddress(beacon.getIpAddress());
    }
    
    @Override
    public Long getId() {
        return id;
    }
    
    @Override
    public final BeaconImpl setId(Long id) {
        this.id = id;
        return this;
    }
    
    @Override
    public Timestamp getCreated() {
        return created;
    }
    
    @Override
    public final BeaconImpl setCreated(Timestamp created) {
        this.created = created;
        return this;
    }
    
    @Override
    public String getIpAddress() {
        return ipAddress;
    }
    
    @Override
    public final BeaconImpl setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
        return this;
    }
    
    @Override
    public Beacon build() {
        return new BeaconImpl(this);
    }
    
    @Override
    public String toString() {
        final StringJoiner sj = new StringJoiner(", ", "{ ", " }");
        sj.add("id = "+Objects.toString(getId()));
        sj.add("created = "+Objects.toString(getCreated()));
        sj.add("ipAddress = "+Objects.toString(getIpAddress()));
        return "BeaconImpl "+sj.toString();
    }
}